version: '3.4'

services:
  web.ui:
    container_name: c_webui
    image: ${DOCKER_REGISTRY-}webui
    build:
      dockerfile: "src/projects/universityAssistant/Clients/webui/Dockerfile"

  web.apigateway:
    container_name: c_apigateway
    image: ${DOCKER_REGISTRY-}webapigateway
    build:
      context: .
      dockerfile: src/projects/universityAssistant/ApiGateways/WebApiGateways/Web.ApiGateway/Dockerfile

  identityservice.api:
    container_name: c_identityservice
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: src/projects/universityAssistant/Services/IdentityService/IdentityService.Api/Dockerfile

  notificationservice.api:
    container_name: c_notificationservice
    image: ${DOCKER_REGISTRY-}notificationserviceapi
    build:
      context: .
      dockerfile: src/projects/universityAssistant/Services/NotificationService/NotificationService.Api/Dockerfile

  storageservice.api:
    container_name: c_storageservice
    image: ${DOCKER_REGISTRY-}storageserviceapi
    build:
      context: .
      dockerfile: src/projects/universityAssistant/Services/StorageService/StorageService.Api/Dockerfile

  universityservice.api:
    container_name: c_universityservice
    image: ${DOCKER_REGISTRY-}universityserviceapi
    build:
      context: .
      dockerfile: src/projects/universityAssistant/Services/UniversityService/Presentation/UniversityService.Api/Dockerfile

  messagepersistenceservice.api:
    container_name: c_messagepersistenceservice
    image: ${DOCKER_REGISTRY-}messagepersistenceserviceapi
    build:
      context: .
      dockerfile: src/projects/universityAssistant/Services/MessagePersistenceService/Presentation/MessagePersistenceService.Api/Dockerfile

  s_consul:
    container_name: c_consul
    image: consul

  s_sqlserver:
    container_name: c_sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest

  s_rabbitmq:
    container_name: c_rabbitmq
    image: rabbitmq:3-management
